### ISSUE TITLE
Posibility to use requirements.txt and virtualenv

### ISSUE THREAD

**Issue by marcorichetta** [HarshShah1997/Shopping-Cart#3]
Hi!
First of all, congrats for this project. It seems pretty complex and the code is very readable.

Regarding the issue, you could add instructions to create a `virtualenv` and, with that, the use of `requirements.txt`, which is very practical for testing projects without messing your system installation.

**Comment by HarshShah1997** [comment]
Added Pipenv. Checkout README for usage instructions.
